Vijith/feat/editor font size
gangofdev/interactive-tutor pull request #9
Opened 2022-09-30 16:31 UTC by vijith07

2022-10-01 05:21 UTC, notshriram requested changes

2022-10-01 05:21 UTC, notshriram commented on package.json
> +    "npm": ">=8.15.0"
Ello Ello Ello. What's all this, then?

2022-10-01 05:21 UTC, notshriram commented on src/components/EditorSettings.tsx
> +                        {({}: any) => (
As mentioned previously. `any` should be used almost never. Here too it can be avoided.

2022-10-01 05:23 UTC, notshriram commented on package.json
> +    "npm": ">=8.15.0"
@akashdoppalapudi do you want to downgrade to 8.15.0?

2022-10-01 17:28 UTC, akashdoppalapudi commented on package.json
> +    "npm": ">=8.15.0"
@notshriram Let's have latest version 8.19.1

2022-10-01 17:29 UTC, akashdoppalapudi commented on src/components/EditorSettings.tsx
> +                        {({}: any) => (
If possible... Let's use interfaces.
let's take advantage of typescript

2022-10-01 17:53 UTC, vijith07 commented on package.json
> +    "npm": ">=8.15.0"
> @notshriram Let's have latest version 8.19.1

why ?

2022-10-02 06:24 UTC, notshriram commented on src/components/EditorSettings.tsx
> +    "text-3xl": "24px",
This does not necessarily correspond to the px values mentioned in the right side.

From [mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/length)
> Represents the [font-size](https://developer.mozilla.org/en-US/docs/Web/CSS/font-size) of the root element (typically [<html>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html)). When used within the root element [font-size](https://developer.mozilla.org/en-US/docs/Web/CSS/font-size), it represents its initial value (a common browser default is 16px, but user-defined preferences may modify this).

So depending on the browser settings, 1 rem could be != 16px

2022-10-02 06:24 UTC, notshriram commented on src/contexts/ThemeContext.tsx
> +  );
👍

2022-10-02 06:24 UTC, notshriram commented on package.json
> +    "npm": ">=8.15.0"
> > @notshriram Let's have latest version 8.19.1
> 
> why ?

https://github.com/npm/cli/blob/latest/CHANGELOG.md#8191-2022-09-01

2022-10-02 06:25 UTC, notshriram approved these changes

2022-10-02 06:26 UTC, merged